### ISSUE TITLE
Can't download the large files 

### ISSUE THREAD

**Issue by FahimKamal** [ubisoft/ubisoft-laforge-ZeroEGGS#19] opened 2022-12-24 09:06 UTC
![image](https://user-images.githubusercontent.com/47342396/209428838-405cd06c-fe21-47e3-a7f0-814d524a3d65.png)

**Comment by vtan05** [comment] 2022-12-30 06:49
I'm also having the same issue. Tried downloading the zip files but they are empty.

**Comment by saeed1262** [comment] 2023-01-11 03:16
duplicate of #20

**Closed by saeed1262** 2023-01-11 03:16 UTC
